### PR TITLE
Graphql schema action

### PR DESCRIPTION
**Pull request by legendofa**
Depends on: https://github.com/MiSArch/wishlist/pull/1

### CODE REVIEW

**Comment by legendofa** [comment]
Secret still needs to be added in the repo settings

**Review by nk-coding — CHANGES_REQUESTED** [review]
Ohm. the schemas dir should be the https://github.com/MiSArch/schemas repo (clone in action, not present in repo otherwise)

**Review by nk-coding — APPROVED** [review]

**Comment by nk-coding** [comment]
> Secret still needs to be added in the repo settings

the secret should already be available as I created it as an organization secret

**Comment by legendofa** [comment]
I already merged it by accident, works fine but contains changes from the other PR :/.

**Pull request merged**
