### PR TITLE
Added protoc runtime dep: CI fixes + Docker Compose fixes, adapted environment variables

### PR DESCRIPTION
**Pull request by legendofa**

### CODE REVIEW

**Comment by legendofa** [comment]
MongoDB credentials can be configured over the connection URI and are not required internally

**Comment by legendofa** [comment]
`docker-compose-dev.yaml` works. Wishlist can't reach the database in `docker-compose-base.yaml`, but `docker-compose-dev.yaml` works as well with the `base-dockerfile`.

**Comment by legendofa** [comment]
> `docker-compose-dev.yaml` works. Wishlist can't reach the database in `docker-compose-base.yaml`, but `docker-compose-dev.yaml` works as well with the `base-dockerfile`.

Nevermind, this was a port mapping issue.

**Review by nk-coding — APPROVED** [review]
I think having a test build github action would be good

**Pull request merged**
