### PR TITLE
GraphQL Federation v2 Support

### PR DESCRIPTION
**Pull request by legendofa**

### CODE REVIEW

**Review by nk-coding — CHANGES_REQUESTED** [review]
- Wishlist currently uses `String` for the `id` field, however this should be `UUID`
- the service should add an `User` and `ProductVariant` and  type which the service does not resolve and which only has an id field
- Wishlist should for `user` then use this new `User` type instead of providing a `userId`
- Wishlist should provide a `ProductVariantConnection` under `productVariants` instead of a list of `productVariantIds`. This should then use the types defined in 
- where did the `wishlist` query whicch gets an Wishlist by id go?

**Comment by legendofa** [comment]
Updated GraphQL Schema:
```graphql
input AddWishlistInput {
	"""
	UUID of user owning the wishlist.
	"""
	userId: UUID!
	"""
	UUIDs of product variants in wishlist.
	"""
	productVariantIds: [UUID!]!
	"""
	Wishlist name.
	"""
	name: String!
}

"""
Specifies the order of foreign types.
"""
input BaseOrder {
	"""
	Order direction of wishlists.
	"""
	direction: OrderDirection
	"""
	Field that wishlists should be ordered by.
	"""
	field: BaseOrderField
}

"""
Describes the fields that a foreign types can be ordered by.

Only the Id valid at the moment.
"""
enum BaseOrderField {
	"""
	Orders by "id".
	"""
	ID
}


scalar DateTime




type Mutation {
	"""
	Adds a wishlist with a user_id, a list of product_variant_ids and a name.
	
	Formats UUIDs as hyphenated lowercase Strings.
	"""
	addWishlist(
		"""
		AddWishlistInput
		"""
		input: AddWishlistInput!
	): Wishlist!
	"""
	Updates name and/or product_variant_ids of a specific wishlist referenced with an id.
	
	Formats UUIDs as hyphenated lowercase Strings.
	"""
	updateWishlist(
		"""
		UpdateWishlistInput
		"""
		input: UpdateWishlistInput!
	): Wishlist!
	"""
	Deletes wishlist of id.
	"""
	deleteWishlist(
		"""
		UUID of wishlist to delete.
		"""
		id: UUID!
	): Boolean!
}

"""
GraphQL order direction.
"""
enum OrderDirection {
	"""
	Ascending order direction.
	"""
	ASC
	"""
	Descending order direction.
	"""
	DESC
}

"""
Foreign type of a product variant.
"""
type ProductVariant @key(fields: "id", resolvable: false) {
	"""
	UUID of the product variant.
	"""
	id: UUID!
}

"""
A connection of ProductVariants.
"""
type ProductVariantConnection @shareable {
	"""
	The resulting entities.
	"""
	nodes: [ProductVariant!]!
	"""
	Whether this connection has a next page.
	"""
	hasNextPage: Boolean!
	"""
	The total amount of items in this connection.
	"""
	totalCount: Int!
}

type Query {
	"""
	Retrieves all wishlists.
	"""
	wishlists(
		"""
		Describes that the `first` N wishlists should be retrieved.
		"""
		first: Int,
		"""
		Describes how many wishlists should be skipped at the beginning.
		"""
		skip: Int,
		"""
		Specifies the order in which wishlists are retrieved.
		"""
		orderBy: WishlistOrder
	): WishlistConnection!
	"""
	Retrieves wishlist of specific id.
	"""
	wishlist(
		"""
		UUID of wishlist to retrieve.
		"""
		id: UUID!
	): Wishlist!
}


scalar UUID

input UpdateWishlistInput {
	"""
	UUID of wishlist to update.
	"""
	id: UUID!
	"""
	product variant UUIDs of wishlist to update
	"""
	productVariantIds: [UUID!]
	"""
	Wishlist name to update
	"""
	name: String
}

"""
Foreign type of a user.
"""
type User @key(fields: "id", resolvable: false) {
	"""
	UUID of the user.
	"""
	id: UUID!
}

"""
The Wishlist of a user.
"""
type Wishlist {
	"""
	Wishlist UUID.
	"""
	id: UUID!
	"""
	User.
	"""
	user: User!
	"""
	Name of Wishlist.
	"""
	name: String!
	"""
	Timestamp when Wishlist was created.
	"""
	createdAt: DateTime!
	"""
	Timestamp when Wishlist was last updated.
	"""
	lastUpdatedAt: DateTime!
	internalProductVariants: [ProductVariant!]!
	"""
	Retrieves product variants.
	"""
	productVariants(
		"""
		Describes that the `first` N wishlists should be retrieved.
		"""
		first: Int,
		"""
		Describes how many wishlists should be skipped at the beginning.
		"""
		skip: Int,
		"""
		Specifies the order in which wishlists are retrieved.
		"""
		orderBy: BaseOrder
	): ProductVariantConnection!
}

"""
A connection of Wishlists.
"""
type WishlistConnection @shareable {
	"""
	The resulting entities.
	"""
	nodes: [Wishlist!]!
	"""
	Whether this connection has a next page.
	"""
	hasNextPage: Boolean!
	"""
	The total amount of items in this connection.
	"""
	totalCount: Int!
}

"""
Specifies the order of wishlists.
"""
input WishlistOrder {
	"""
	Order direction of wishlists.
	"""
	direction: OrderDirection
	"""
	Field that wishlists should be ordered by.
	"""
	field: WishlistOrderField
}

"""
Describes the fields that a wishlist can be ordered by.
"""
enum WishlistOrderField {
	"""
	Orders by "id".
	"""
	ID
	"""
	Orders by "user_id".
	"""
	USER_ID
	"""
	Orders by "name".
	"""
	NAME
	"""
	Orders by "created_at".
	"""
	CREATED_AT
	"""
	Orders by "last_updated_at".
	"""
	LAST_UPDATED_AT
}

extend schema @link(
	url: "https://specs.apollo.dev/federation/v2.3",
	import: ["@key", "@tag", "@shareable", "@inaccessible", "@override", "@external", "@provides", "@requires", "@composeDirective", "@interfaceObject"]
)
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

```

**Review by nk-coding — CHANGES_REQUESTED** [review]
According to our ADR (https://misarch.github.io/docs/dev-manuals/adr/graphql-connections) some minor naming changes
- BaseOrderField  => CommonOrderField
- BaseOrder => CommonOrderInput
- WishlistOrder => WishlistOrderInput

Other things:
- Wishlist is missing the `key` decorator
- `internalProductVariants`: should this be exposed in the schema? it also has no documentation

**Comment by legendofa** [comment]
> According to our ADR (https://misarch.github.io/docs/dev-manuals/adr/graphql-connections) some minor naming changes
> 
>     * BaseOrderField  => CommonOrderField
> 
>     * BaseOrder => CommonOrderInput
> 
>     * WishlistOrder => WishlistOrderInput
> 
> 
> Other things:
> 
>     * Wishlist is missing the `key` decorator
> 
>     * `internalProductVariants`: should this be exposed in the schema? it also has no documentation

Will fix!

**Comment by legendofa** [comment]
`internalProductVariants` is hidden as it should be. This is for implementing the `ProductVariantConnection`

**Comment by legendofa** [comment]
`Wishlist is missing the key decorator`

This is solved when i make the `wishlist` query an Entity with a decorator, but then the query disappears, not sure what is going on there.

**Comment by nk-coding** [comment]
> `Wishlist is missing the key decorator`
> 
> This is solved when i make the `wishlist` query an Entity with a decorator, but then the query disappears, not sure what is going on there.

my guess would be that it then treats it as the entity resolver
you probably need to add the wishlist query additionally

**Comment by legendofa** [comment]
> > `Wishlist is missing the key decorator`
> > This is solved when i make the `wishlist` query an Entity with a decorator, but then the query disappears, not sure what is going on there.
> 
> my guess would be that it then treats it as the entity resolver you probably need to add the wishlist query additionally

Looks like it, i have added a separate `wishlist` query now.

**Comment by legendofa** [comment]
Updated GraphQL Schema:

```graphql
input AddWishlistInput {
	"""
	UUID of user owning the wishlist.
	"""
	userId: UUID!
	"""
	UUIDs of product variants in wishlist.
	"""
	productVariantIds: [UUID!]!
	"""
	Wishlist name.
	"""
	name: String!
}


"""
Describes the fields that a foreign types can be ordered by.

Only the Id valid at the moment.
"""
enum CommonOrderField {
	"""
	Orders by "id".
	"""
	ID
}

"""
Specifies the order of foreign types.
"""
input CommonOrderInput {
	"""
	Order direction of wishlists.
	"""
	direction: OrderDirection
	"""
	Field that wishlists should be ordered by.
	"""
	field: CommonOrderField
}

scalar DateTime




type Mutation {
	"""
	Adds a wishlist with a user_id, a list of product_variant_ids and a name.
	
	Formats UUIDs as hyphenated lowercase Strings.
	"""
	addWishlist(
		"""
		AddWishlistInput
		"""
		input: AddWishlistInput!
	): Wishlist!
	"""
	Updates name and/or product_variant_ids of a specific wishlist referenced with an id.
	
	Formats UUIDs as hyphenated lowercase Strings.
	"""
	updateWishlist(
		"""
		UpdateWishlistInput
		"""
		input: UpdateWishlistInput!
	): Wishlist!
	"""
	Deletes wishlist of id.
	"""
	deleteWishlist(
		"""
		UUID of wishlist to delete.
		"""
		id: UUID!
	): Boolean!
}

"""
GraphQL order direction.
"""
enum OrderDirection {
	"""
	Ascending order direction.
	"""
	ASC
	"""
	Descending order direction.
	"""
	DESC
}

"""
Foreign type of a product variant.
"""
type ProductVariant @key(fields: "id", resolvable: false) {
	"""
	UUID of the product variant.
	"""
	id: UUID!
}

"""
A connection of ProductVariants.
"""
type ProductVariantConnection @shareable {
	"""
	The resulting entities.
	"""
	nodes: [ProductVariant!]!
	"""
	Whether this connection has a next page.
	"""
	hasNextPage: Boolean!
	"""
	The total amount of items in this connection.
	"""
	totalCount: Int!
}

type Query {
	"""
	Retrieves all wishlists.
	"""
	wishlists(
		"""
		Describes that the `first` N wishlists should be retrieved.
		"""
		first: Int,
		"""
		Describes how many wishlists should be skipped at the beginning.
		"""
		skip: Int,
		"""
		Specifies the order in which wishlists are retrieved.
		"""
		orderBy: WishlistOrderInput
	): WishlistConnection!
	"""
	Retrieves wishlist of specific id.
	"""
	wishlist(
		"""
		UUID of wishlist to retrieve.
		"""
		id: UUID!
	): Wishlist!
}


scalar UUID

input UpdateWishlistInput {
	"""
	UUID of wishlist to update.
	"""
	id: UUID!
	"""
	product variant UUIDs of wishlist to update
	"""
	productVariantIds: [UUID!]
	"""
	Wishlist name to update
	"""
	name: String
}

"""
Foreign type of a user.
"""
type User @key(fields: "id", resolvable: false) {
	"""
	UUID of the user.
	"""
	id: UUID!
}

"""
The Wishlist of a user.
"""
type Wishlist @key(fields: "id") {
	"""
	Wishlist UUID.
	"""
	id: UUID!
	"""
	User.
	"""
	user: User!
	"""
	Name of Wishlist.
	"""
	name: String!
	"""
	Timestamp when Wishlist was created.
	"""
	createdAt: DateTime!
	"""
	Timestamp when Wishlist was last updated.
	"""
	lastUpdatedAt: DateTime!
	internalProductVariants: [ProductVariant!]!
	"""
	Retrieves product variants.
	"""
	productVariants(
		"""
		Describes that the `first` N wishlists should be retrieved.
		"""
		first: Int,
		"""
		Describes how many wishlists should be skipped at the beginning.
		"""
		skip: Int,
		"""
		Specifies the order in which wishlists are retrieved.
		"""
		orderBy: CommonOrderInput
	): ProductVariantConnection!
}

"""
A connection of Wishlists.
"""
type WishlistConnection @shareable {
	"""
	The resulting entities.
	"""
	nodes: [Wishlist!]!
	"""
	Whether this connection has a next page.
	"""
	hasNextPage: Boolean!
	"""
	The total amount of items in this connection.
	"""
	totalCount: Int!
}

"""
Describes the fields that a wishlist can be ordered by.
"""
enum WishlistOrderField {
	"""
	Orders by "id".
	"""
	ID
	"""
	Orders by "user_id".
	"""
	USER_ID
	"""
	Orders by "name".
	"""
	NAME
	"""
	Orders by "created_at".
	"""
	CREATED_AT
	"""
	Orders by "last_updated_at".
	"""
	LAST_UPDATED_AT
}

"""
Specifies the order of wishlists.
"""
input WishlistOrderInput {
	"""
	Order direction of wishlists.
	"""
	direction: OrderDirection
	"""
	Field that wishlists should be ordered by.
	"""
	field: WishlistOrderField
}

extend schema @link(
	url: "https://specs.apollo.dev/federation/v2.3",
	import: ["@key", "@tag", "@shareable", "@inaccessible", "@override", "@external", "@provides", "@requires", "@composeDirective", "@interfaceObject"]
)
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT

```

**Review by nk-coding — APPROVED** [review]
Looks good to me

**Pull request merged**
